export const REQUEST_CURRENCIES_LIST_PENDING = 'REQUEST_CURRENCIES_LIST_PENDING';
export const REQUEST_CURRENCIES_LIST_SUCCESS = 'REQUEST_CURRENCIES_LIST_SUCCESS';
export const REQUEST_CURRENCIES_LIST_FAILURE = 'REQUEST_CURRENCIES_LIST_FAILURE';

export const REQUEST_CURRENCIES_CONVERT_PENDING = 'REQUEST_CURRENCIES_CONVERT_PENDING';
export const REQUEST_CURRENCIES_CONVERT_SUCCESS = 'REQUEST_CURRENCIES_CONVERT_SUCCESS';
export const REQUEST_CURRENCIES_CONVERT_FAILURE = 'REQUEST_CURRENCIES_CONVERT_FAILURE';