export const REQUEST_STATS_TOP_PENDING = 'REQUEST_STATS_TOP_PENDING';
export const REQUEST_STATS_TOP_SUCCESS = 'REQUEST_STATS_TOP_SUCCESS';
export const REQUEST_STATS_TOP_FAILURE = 'REQUEST_STATS_TOP_FAILURE';

export const REQUEST_STATS_USAGE_PENDING = 'REQUEST_STATS_USAGE_PENDING';
export const REQUEST_STATS_USAGE_SUCCESS = 'REQUEST_STATS_USAGE_SUCCESS';
export const REQUEST_STATS_USAGE_FAILURE = 'REQUEST_STATS_USAGE_FAILURE';

export const TOGGLE_TOP_MODAL = 'TOGGLE_TOP_MODAL';
export const TOGGLE_USAGE_MODAL = 'TOGGLE_USAGE_MODAL';